version: '3.2'

services:
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    ports:
      - "${API_PORT:-4000}:4000"
    # env_file:
    #   - ./apps/api/.env
    environment:
      - NODE_ENV=production

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    ports:
      - "${WEB_PORT:-3001}:3000"
    env_file:
      - ./apps/web/.env
    environment:
      - NODE_ENV=production
    depends_on:
      - api 