packages:
  - 'apps/*'
  - 'packages/*'

catalog:
  tailwindcss: ^4.1.3
  '@tailwindcss/cli': ^4.1.4
  '@tailwindcss/postcss': ^4.1.3
  postcss: ^8.5.3
  'zod': '^3.24.3'
  'dotenv': '^16.5.0'
  'dotenv-expand': ^12.0.2
